### ISSUE TITLE
Inicializado front.

### ISSUE THREAD

**Issue by daal-imd** [daal-imd/integraTI-api#4]
Desculpem a demora, mas fim de semestre acredito que fica complicado darmos algum sinal de vida aqui no projeto. Inicializei a parte do front do projeto em react js, numa disciplina de Gerência e Configuração de Mudança, a partir dele podemos criar as rotas e dar novas funcionalidades, tudo isso foi feito com base no questionário realizado junto ao corpo discente do BTI. Segue o link: https://integra-ti.netlify.com
Por sinal, gostei muito dessa plataforma [netlify](https://www.netlify.com/) que permite o deploy automático e é gratuito.

**Comment by weslenbreno** [comment]
Onde está o código ?

**Comment by weslenbreno** [comment]
Gostei pra caramba desse Netlify, muito prático. Obrigado pela sugestão.

**Comment by gellyviana** [comment]
olá @weslenbreno, queria que vcs aprovassem, porque esse projeto fiz justamente para contribuir com a comunidade, por enquanto projeto está no meu [gitlab](https://gitlab.com/gellyviana/integra-ti.git), mas quero adicioná-lo aqui. Espero que gostem.
